Repository graphprocessing/graph_coarsening, pull requests merged in 2019-02, with the labels that each got.

#4 Reorganized pipeline structure
  build.py
  modules/pipelines/evaluator.h
  modules/pipelines/launch.h
  modules/pipelines/pipeline_management.h
  modules/pipelines/pipeline_sample.h
  modules/pipelines/prepare.h
  samples/example_bio/bio.cpp
  samples/example_main/main.cpp
  scripts/pipelines_table.py
Labels: enhancement

#7 Added tests for algorithms, fixed zadeh_test and others
  .travis.yml
  benchmark/include/example_benchmark_test.h
  benchmark/source/example_benchmark_test.cpp
  benchmark/source/run_tests.cpp
  build.py
  modules/generators/include/zadeh_test.h
  tests/include/example_parametric_test.h
  tests/source/al_test.cpp
  tests/source/algorithms_test.cpp
  tests/source/csr_test.cpp
  tests/source/random_matching_test.cpp
  tests/source/run_tests.cpp
Labels: wontfix

#9 Dependency removal.
  .travis.yml
  CMakeLists.txt
  README.md
  appveyor.yml
  build.py
  cmake/cpplint.cmake
  modules/algorithms/include/find_bridges.h
  modules/algorithms/include/find_joint_points.h
  modules/algorithms/include/floyd_warshall.h
  modules/algorithms/include/graph_coarsening.h
  modules/algorithms/include/graph_distances.h
  modules/algorithms/include/hard_matching.h
  modules/algorithms/include/minimal_spanning_tree.h
  modules/algorithms/include/random_matching.h
  modules/algorithms/include/strongly_connected_components.h
  modules/common/include/dsu.h
  modules/common/include/export.h
  modules/common/include/randomize.h
  modules/data_structures/include/adjacency_list.h
  modules/data_structures/include/csr.h
  modules/data_structures/include/graph.h
  modules/data_structures/include/jds.h
  modules/data_structures/include/matching.h
  modules/pch/include/precomp.h
  modules/pipelines/evaluator.h
  modules/pipelines/pipeline_management.h
  modules/pipelines/pipeline_sample.h
  tests/include/hard_matching_parametric_test.h
  tests/include/random_matching_parametric_test.h
Labels: wontfix

#10 Revert "Dependency removal."
  .travis.yml
  CMakeLists.txt
  README.md
  appveyor.yml
  build.py
  cmake/cpplint.cmake
  modules/algorithms/include/find_bridges.h
  modules/algorithms/include/find_joint_points.h
  modules/algorithms/include/floyd_warshall.h
  modules/algorithms/include/graph_coarsening.h
  modules/algorithms/include/graph_distances.h
  modules/algorithms/include/hard_matching.h
  modules/algorithms/include/minimal_spanning_tree.h
  modules/algorithms/include/random_matching.h
  modules/algorithms/include/strongly_connected_components.h
  modules/common/include/dsu.h
  modules/common/include/export.h
  modules/common/include/randomize.h
  modules/data_structures/include/adjacency_list.h
  modules/data_structures/include/csr.h
  modules/data_structures/include/graph.h
  modules/data_structures/include/jds.h
  modules/data_structures/include/matching.h
  modules/pch/include/precomp.h
  modules/pipelines/evaluator.h
  modules/pipelines/pipeline_management.h
  modules/pipelines/pipeline_sample.h
  tests/include/hard_matching_parametric_test.h
  tests/include/random_matching_parametric_test.h
Labels: bug, wontfix

#12 Updated build.py
  appveyor.yml
  build.py
Labels: duplicate

#24 Graph_coarsening_2.0
  modules/algorithms/include/graph_coarsening.h
Labels: duplicate

#37 Convert to undirected graph
  modules/common/include/import.h
  modules/data_structures/include/adjacency_list.h
  modules/pch/include/precomp.h
  samples/example_main/main.cpp
Labels: invalid

#38 Pipelines improvement
  build.py
  modules/pipelines/evaluator.h
  modules/pipelines/pipeline_coarsening_random.h
  modules/pipelines/pipeline_management.h
  modules/pipelines/pipeline_sample.h
  samples/example_bio/bio.cpp
  scripts/pipelines_table.py
Labels: enhancement

#41 Hotfix for new version of cpplint
  build.py
Labels: bug

#43 Fixed bugs related to double and updated example_bio
  modules/algorithms/include/floyd_warshall.h
  modules/algorithms/include/graph_distances.h
  modules/algorithms/include/minimal_spanning_tree.h
  modules/pipelines/evaluator.h
  samples/example_bio/bio.cpp
Labels: enhancement

#44 change int on Weightype
  modules/algorithms/include/hard_matching.h
Labels: bug
